<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\Mappers\Mappers.csproj" />
    <ProjectReference Include="..\Helpers\Helpers.csproj" />
    <ProjectReference Include="..\OpCodes\OpCodes.csproj" />
    <ProjectReference Include="..\Components\Components.csproj" />
    <ProjectReference Include="..\AddressingModes\AddressingModes.csproj" />
  </ItemGroup>


</Project>
