using AddressingModes;
using Interfaces;
using OpCodes;

namespace Chips;

public record Instruction : IInstruction
{
    public string Name { get; init; }
    public int Cycles { get; init; }
    public IAddressingMode AddressingMode { get; init; }
    public IOpCode Operation { get; init; }

    public Instruction(string name, IOpCode operation, IAddressingMode addressingMode, int cycles)
    {
        Name = name;
        Cycles = cycles;
        AddressingMode = addressingMode;
        Operation = operation;
    }

    private static Instruction[] BuildInstructionSet()
    {
        var instructions = new Instruction[]
        {
                new Instruction( "BRK", ProcessorInstructions.BRK, InstructionAddressingModes.Immediate, 7 ),new Instruction( "ORA", ProcessorInstructions.ORA, InstructionAddressingModes.IndirectX, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 3 ),new Instruction( "ORA", ProcessorInstructions.ORA, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "ASL", ProcessorInstructions.ASL, InstructionAddressingModes.ZeroPage, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 5 ),new Instruction( "PHP", ProcessorInstructions.PHP, InstructionAddressingModes.Implied, 3 ),new Instruction( "ORA", ProcessorInstructions.ORA, InstructionAddressingModes.Immediate, 2 ),new Instruction( "ASL", ProcessorInstructions.ASL, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "ORA", ProcessorInstructions.ORA, InstructionAddressingModes.Absolute, 4 ),new Instruction( "ASL", ProcessorInstructions.ASL, InstructionAddressingModes.Absolute, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),
                new Instruction( "BPL", ProcessorInstructions.BPL, InstructionAddressingModes.Relative, 2 ),new Instruction( "ORA", ProcessorInstructions.ORA, InstructionAddressingModes.IndirectY, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "ORA", ProcessorInstructions.ORA, InstructionAddressingModes.ZeroPageX, 4 ),new Instruction( "ASL", ProcessorInstructions.ASL, InstructionAddressingModes.ZeroPageX, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),new Instruction( "CLC", ProcessorInstructions.CLC, InstructionAddressingModes.Implied, 2 ),new Instruction( "ORA", ProcessorInstructions.ORA, InstructionAddressingModes.AbsoluteY, 4 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "ORA", ProcessorInstructions.ORA, InstructionAddressingModes.AbsoluteX, 4 ),new Instruction( "ASL", ProcessorInstructions.ASL, InstructionAddressingModes.AbsoluteX, 7 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),
                new Instruction( "JSR", ProcessorInstructions.JSR, InstructionAddressingModes.Absolute, 6 ),new Instruction( "AND", ProcessorInstructions.AND, InstructionAddressingModes.IndirectX, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "BIT", ProcessorInstructions.BIT, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "AND", ProcessorInstructions.AND, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "ROL", ProcessorInstructions.ROL, InstructionAddressingModes.ZeroPage, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 5 ),new Instruction( "PLP", ProcessorInstructions.PLP, InstructionAddressingModes.Implied, 4 ),new Instruction( "AND", ProcessorInstructions.AND, InstructionAddressingModes.Immediate, 2 ),new Instruction( "ROL", ProcessorInstructions.ROL, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "BIT", ProcessorInstructions.BIT, InstructionAddressingModes.Absolute, 4 ),new Instruction( "AND", ProcessorInstructions.AND, InstructionAddressingModes.Absolute, 4 ),new Instruction( "ROL", ProcessorInstructions.ROL, InstructionAddressingModes.Absolute, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),
                new Instruction( "BMI", ProcessorInstructions.BMI, InstructionAddressingModes.Relative, 2 ),new Instruction( "AND", ProcessorInstructions.AND, InstructionAddressingModes.IndirectY, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "AND", ProcessorInstructions.AND, InstructionAddressingModes.ZeroPageX, 4 ),new Instruction( "ROL", ProcessorInstructions.ROL, InstructionAddressingModes.ZeroPageX, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),new Instruction( "SEC", ProcessorInstructions.SEC, InstructionAddressingModes.Implied, 2 ),new Instruction( "AND", ProcessorInstructions.AND, InstructionAddressingModes.AbsoluteY, 4 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "AND", ProcessorInstructions.AND, InstructionAddressingModes.AbsoluteX, 4 ),new Instruction( "ROL", ProcessorInstructions.ROL, InstructionAddressingModes.AbsoluteX, 7 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),
                new Instruction( "RTI", ProcessorInstructions.RTI, InstructionAddressingModes.Implied, 6 ),new Instruction( "EOR", ProcessorInstructions.EOR, InstructionAddressingModes.IndirectX, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 3 ),new Instruction( "EOR", ProcessorInstructions.EOR, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "LSR", ProcessorInstructions.LSR, InstructionAddressingModes.ZeroPage, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 5 ),new Instruction( "PHA", ProcessorInstructions.PHA, InstructionAddressingModes.Implied, 3 ),new Instruction( "EOR", ProcessorInstructions.EOR, InstructionAddressingModes.Immediate, 2 ),new Instruction( "LSR", ProcessorInstructions.LSR, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "JMP", ProcessorInstructions.JMP, InstructionAddressingModes.Absolute, 3 ),new Instruction( "EOR", ProcessorInstructions.EOR, InstructionAddressingModes.Absolute, 4 ),new Instruction( "LSR", ProcessorInstructions.LSR, InstructionAddressingModes.Absolute, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),
                new Instruction( "BVC", ProcessorInstructions.BVC, InstructionAddressingModes.Relative, 2 ),new Instruction( "EOR", ProcessorInstructions.EOR, InstructionAddressingModes.IndirectY, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "EOR", ProcessorInstructions.EOR, InstructionAddressingModes.ZeroPageX, 4 ),new Instruction( "LSR", ProcessorInstructions.LSR, InstructionAddressingModes.ZeroPageX, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),new Instruction( "CLI", ProcessorInstructions.CLI, InstructionAddressingModes.Implied, 2 ),new Instruction( "EOR", ProcessorInstructions.EOR, InstructionAddressingModes.AbsoluteY, 4 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "EOR", ProcessorInstructions.EOR, InstructionAddressingModes.AbsoluteX, 4 ),new Instruction( "LSR", ProcessorInstructions.LSR, InstructionAddressingModes.AbsoluteX, 7 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),
                new Instruction( "RTS", ProcessorInstructions.RTS, InstructionAddressingModes.Implied, 6 ),new Instruction( "ADC", ProcessorInstructions.ADC, InstructionAddressingModes.IndirectX, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 3 ),new Instruction( "ADC", ProcessorInstructions.ADC, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "ROR", ProcessorInstructions.ROR, InstructionAddressingModes.ZeroPage, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 5 ),new Instruction( "PLA", ProcessorInstructions.PLA, InstructionAddressingModes.Implied, 4 ),new Instruction( "ADC", ProcessorInstructions.ADC, InstructionAddressingModes.Immediate, 2 ),new Instruction( "ROR", ProcessorInstructions.ROR, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "JMP", ProcessorInstructions.JMP, InstructionAddressingModes.Indirect, 5 ),new Instruction( "ADC", ProcessorInstructions.ADC, InstructionAddressingModes.Absolute, 4 ),new Instruction( "ROR", ProcessorInstructions.ROR, InstructionAddressingModes.Absolute, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),
                new Instruction( "BVS", ProcessorInstructions.BVS, InstructionAddressingModes.Relative, 2 ),new Instruction( "ADC", ProcessorInstructions.ADC, InstructionAddressingModes.IndirectY, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "ADC", ProcessorInstructions.ADC, InstructionAddressingModes.ZeroPageX, 4 ),new Instruction( "ROR", ProcessorInstructions.ROR, InstructionAddressingModes.ZeroPageX, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),new Instruction( "SEI", ProcessorInstructions.SEI, InstructionAddressingModes.Implied, 2 ),new Instruction( "ADC", ProcessorInstructions.ADC, InstructionAddressingModes.AbsoluteY, 4 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "ADC", ProcessorInstructions.ADC, InstructionAddressingModes.AbsoluteX, 4 ),new Instruction( "ROR", ProcessorInstructions.ROR, InstructionAddressingModes.AbsoluteX, 7 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),
                new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "STA", ProcessorInstructions.STA, InstructionAddressingModes.IndirectX, 6 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),new Instruction( "STY", ProcessorInstructions.STY, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "STA", ProcessorInstructions.STA, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "STX", ProcessorInstructions.STX, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 3 ),new Instruction( "DEY", ProcessorInstructions.DEY, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "TXA", ProcessorInstructions.TXA, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "STY", ProcessorInstructions.STY, InstructionAddressingModes.Absolute, 4 ),new Instruction( "STA", ProcessorInstructions.STA, InstructionAddressingModes.Absolute, 4 ),new Instruction( "STX", ProcessorInstructions.STX, InstructionAddressingModes.Absolute, 4 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 4 ),
                new Instruction( "BCC", ProcessorInstructions.BCC, InstructionAddressingModes.Relative, 2 ),new Instruction( "STA", ProcessorInstructions.STA, InstructionAddressingModes.IndirectY, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),new Instruction( "STY", ProcessorInstructions.STY, InstructionAddressingModes.ZeroPageX, 4 ),new Instruction( "STA", ProcessorInstructions.STA, InstructionAddressingModes.ZeroPageX, 4 ),new Instruction( "STX", ProcessorInstructions.STX, InstructionAddressingModes.ZeroPageY, 4 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 4 ),new Instruction( "TYA", ProcessorInstructions.TYA, InstructionAddressingModes.Implied, 2 ),new Instruction( "STA", ProcessorInstructions.STA, InstructionAddressingModes.AbsoluteY, 5 ),new Instruction( "TXS", ProcessorInstructions.TXS, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 5 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 5 ),new Instruction( "STA", ProcessorInstructions.STA, InstructionAddressingModes.AbsoluteX, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 5 ),
                new Instruction( "LDY", ProcessorInstructions.LDY, InstructionAddressingModes.Immediate, 2 ),new Instruction( "LDA", ProcessorInstructions.LDA, InstructionAddressingModes.IndirectX, 6 ),new Instruction( "LDX", ProcessorInstructions.LDX, InstructionAddressingModes.Immediate, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),new Instruction( "LDY", ProcessorInstructions.LDY, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "LDA", ProcessorInstructions.LDA, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "LDX", ProcessorInstructions.LDX, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 3 ),new Instruction( "TAY", ProcessorInstructions.TAY, InstructionAddressingModes.Implied, 2 ),new Instruction( "LDA", ProcessorInstructions.LDA, InstructionAddressingModes.Immediate, 2 ),new Instruction( "TAX", ProcessorInstructions.TAX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "LDY", ProcessorInstructions.LDY, InstructionAddressingModes.Absolute, 4 ),new Instruction( "LDA", ProcessorInstructions.LDA, InstructionAddressingModes.Absolute, 4 ),new Instruction( "LDX", ProcessorInstructions.LDX, InstructionAddressingModes.Absolute, 4 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 4 ),
                new Instruction( "BCS", ProcessorInstructions.BCS, InstructionAddressingModes.Relative, 2 ),new Instruction( "LDA", ProcessorInstructions.LDA, InstructionAddressingModes.IndirectY, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 5 ),new Instruction( "LDY", ProcessorInstructions.LDY, InstructionAddressingModes.ZeroPageX, 4 ),new Instruction( "LDA", ProcessorInstructions.LDA, InstructionAddressingModes.ZeroPageX, 4 ),new Instruction( "LDX", ProcessorInstructions.LDX, InstructionAddressingModes.ZeroPageY, 4 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 4 ),new Instruction( "CLV", ProcessorInstructions.CLV, InstructionAddressingModes.Implied, 2 ),new Instruction( "LDA", ProcessorInstructions.LDA, InstructionAddressingModes.AbsoluteY, 4 ),new Instruction( "TSX", ProcessorInstructions.TSX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 4 ),new Instruction( "LDY", ProcessorInstructions.LDY, InstructionAddressingModes.AbsoluteX, 4 ),new Instruction( "LDA", ProcessorInstructions.LDA, InstructionAddressingModes.AbsoluteX, 4 ),new Instruction( "LDX", ProcessorInstructions.LDX, InstructionAddressingModes.AbsoluteY, 4 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 4 ),
                new Instruction( "CPY", ProcessorInstructions.CPY, InstructionAddressingModes.Immediate, 2 ),new Instruction( "CMP", ProcessorInstructions.CMP, InstructionAddressingModes.IndirectX, 6 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "CPY", ProcessorInstructions.CPY, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "CMP", ProcessorInstructions.CMP, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "DEC", ProcessorInstructions.DEC, InstructionAddressingModes.ZeroPage, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 5 ),new Instruction( "INY", ProcessorInstructions.INY, InstructionAddressingModes.Implied, 2 ),new Instruction( "CMP", ProcessorInstructions.CMP, InstructionAddressingModes.Immediate, 2 ),new Instruction( "DEX", ProcessorInstructions.DEX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "CPY", ProcessorInstructions.CPY, InstructionAddressingModes.Absolute, 4 ),new Instruction( "CMP", ProcessorInstructions.CMP, InstructionAddressingModes.Absolute, 4 ),new Instruction( "DEC", ProcessorInstructions.DEC, InstructionAddressingModes.Absolute, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),
                new Instruction( "BNE", ProcessorInstructions.BNE, InstructionAddressingModes.Relative, 2 ),new Instruction( "CMP", ProcessorInstructions.CMP, InstructionAddressingModes.IndirectY, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "CMP", ProcessorInstructions.CMP, InstructionAddressingModes.ZeroPageX, 4 ),new Instruction( "DEC", ProcessorInstructions.DEC, InstructionAddressingModes.ZeroPageX, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),new Instruction( "CLD", ProcessorInstructions.CLD, InstructionAddressingModes.Implied, 2 ),new Instruction( "CMP", ProcessorInstructions.CMP, InstructionAddressingModes.AbsoluteY, 4 ),new Instruction( "NOP", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "CMP", ProcessorInstructions.CMP, InstructionAddressingModes.AbsoluteX, 4 ),new Instruction( "DEC", ProcessorInstructions.DEC, InstructionAddressingModes.AbsoluteX, 7 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),
                new Instruction( "CPX", ProcessorInstructions.CPX, InstructionAddressingModes.Immediate, 2 ),new Instruction( "SBC", ProcessorInstructions.SBC, InstructionAddressingModes.IndirectX, 6 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "CPX", ProcessorInstructions.CPX, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "SBC", ProcessorInstructions.SBC, InstructionAddressingModes.ZeroPage, 3 ),new Instruction( "INC", ProcessorInstructions.INC, InstructionAddressingModes.ZeroPage, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 5 ),new Instruction( "INX", ProcessorInstructions.INX, InstructionAddressingModes.Implied, 2 ),new Instruction( "SBC", ProcessorInstructions.SBC, InstructionAddressingModes.Immediate, 2 ),new Instruction( "NOP", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.SBC, InstructionAddressingModes.Implied, 2 ),new Instruction( "CPX", ProcessorInstructions.CPX, InstructionAddressingModes.Absolute, 4 ),new Instruction( "SBC", ProcessorInstructions.SBC, InstructionAddressingModes.Absolute, 4 ),new Instruction( "INC", ProcessorInstructions.INC, InstructionAddressingModes.Absolute, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),
                new Instruction( "BEQ", ProcessorInstructions.BEQ, InstructionAddressingModes.Relative, 2 ),new Instruction( "SBC", ProcessorInstructions.SBC, InstructionAddressingModes.IndirectY, 5 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 8 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "SBC", ProcessorInstructions.SBC, InstructionAddressingModes.ZeroPageX, 4 ),new Instruction( "INC", ProcessorInstructions.INC, InstructionAddressingModes.ZeroPageX, 6 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 6 ),new Instruction( "SED", ProcessorInstructions.SED, InstructionAddressingModes.Implied, 2 ),new Instruction( "SBC", ProcessorInstructions.SBC, InstructionAddressingModes.AbsoluteY, 4 ),new Instruction( "NOP", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 2 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),new Instruction( "???", ProcessorInstructions.NOP, InstructionAddressingModes.Implied, 4 ),new Instruction( "SBC", ProcessorInstructions.SBC, InstructionAddressingModes.AbsoluteX, 4 ),new Instruction( "INC", ProcessorInstructions.INC, InstructionAddressingModes.AbsoluteX, 7 ),new Instruction( "???", ProcessorInstructions.XXX, InstructionAddressingModes.Implied, 7 ),
        };

        return instructions;
    }

    private static IInstruction[] _lookupInstructionsTable = BuildInstructionSet();

    public static IInstruction GetInstruction(int opCode)
    {
        return _lookupInstructionsTable[opCode];
    }
}
